version: "1.0"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
        - 80:3000
    environment:
        - /src/seo.env
    tty: true
  app:
    image: node:19-alpine
    container_name: SEO
    command: sh -c "npm init -y && yarn install && yarn run env"
    ports:
      - 5432:5432
    working_dir: /src
    environment:
      - /src/seo.env
    healthcheck:
      test: pg_isready -d postgres -U root
      interval: 10s
      timeout: 5s
      retries: 10
  db:
    image: postgres:15.2-bullseye
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=admin
volumes:
  dbdata: