services:
  redis:
    image: redis

  app:
    image: node:19-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 5000:5000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: todos

  postgres:
    image: postgres:15.2-bullseye
    volumes:
      - test:/var/lib/postgres
    environment:
      POSTGRES_ROOT_PASSWORD: secret
      POSTGRES_DATABASE: todos

volumes:
  test: